### PR TITLE
Update es_ES.md

### PR DESCRIPTION
**Pull request by sarahfathallah**

### CODE REVIEW

**Comment by jwishnie** [comment]
Hi Sarah,

Take a look at the newly submitted es_MX.md -- it seems pretty similar to your suggested changes.

Do you feel the current language in es_ES.md is appropriate for a Castellano translation?

Por ejemplo, 'profesional del disnño' en vez de 'diseñador' ?

**Comment by sarahfathallah** [comment]
"Profesional del diseño" sounds oddly redundant to me, but happy to defer to a native Castilian speaker.

**Comment by jwishnie** [comment]
Sounds a little awkward to me as well. But I learned my Spanish from Catalans so... ;-)

Let's ask @arianaescobar ! 

@arianaescobar : what do you think of the suggested changes from @sarahfathallah ?

**Comment by arianaescobar** [comment]
Hey! @jwishnie @sarahfathallah 

It does sound a bit strange but what we wanted to avoid was the use of the masculine word `Diseñador` to be more inclusive. `Designer` doesn't have that issue because it works for any gender identity but in Spanish, we could also say `Diseñadora`.

**Comment by sarahfathallah** [comment]
@arianaescobar That actually applies even with the use of "profesional del diseño," depending on whether you choose to put the determiner "el" or "la" in front of it.

But I agree this is an issue, not just for Spanish, but all gendered languages. (For both French and Arabic at the moment, either the noun or the determiner assumes a masculine attribute.) Cc @jwishnie @mmmonteiro

**Comment by arianaescobar** [comment]
Yes, you're right. That's the discussion we've been having in the first couple of pull requests for the Spanish translation. Tricky subject 😅

**Pull request merged**
