### PR TITLE
Create ar.md

### PR DESCRIPTION
**Pull request by sarahfathallah**

### CODE REVIEW

**Comment by jwishnie** [comment]
@sarahfathallah I've merged but am wondering if this should be a more specific regional dialect. 

What dialect is this translation in (e.g. MSA, Egyptian, Jordanian etc...)? (sorry,  I can't read Arabic, I only know that my Arabic speaking friends tell me there are clear distinctions... At least spoken!)

**Comment by sarahfathallah** [comment]
@jwishnie This is MSA, which is why adding a country code after it didn't really apply.

**Comment by jwishnie** [comment]
Perfect! Thank you!

**Comment by jwishnie** [comment]
@sarahfathallah in the READ.md me I used العَرَبِيَّة (al arabiyya) as the label. Is that correct or would you use the shorter (less formal?) عَرَبِيّ (arabi)?

**Comment by sarahfathallah** [comment]
العربية is fine!

**Comment by jwishnie** [comment]
👍🏾

**Pull request merged**
