### PR TITLE
Beginning of the Spanish translation.

### PR DESCRIPTION
**Pull request by ghost**
Designer does not have a neutral grammatical gender in Spanish, hence I avoided the direct translation of Designer to _Diseñador_ that will exclude female Designers. Instead I have tried to use a more inclusive language. I would love comments on this, in case there is a more accurate translation.

### CODE REVIEW

**Comment by axelvaldez** [comment]
Hi @cplazuelo. Your translation says "Porfesional" instead of "Profesional". Thought you should know before the pull request goes through.

**Comment by jwishnie** [comment]
File name should be es.md for 'generic' Spanish, or es_COUNTRYCODE.md for regional dialects.

E.g. es_ES.md for 'Spanish' Spanish (Castellano); es_MX.md for Mexican spanish etc...

**Review by alexcamlo — CHANGES_REQUESTED** [review]
Change Porfesional to Profesional
Change file name to es_ES.md

**Comment by arianaescobar** [comment]
If you are going to use "El/La ..." you might as well just put "Un diseñador/a" 🤔

**Comment by ghost** [comment]
@jwishnie @thewinger I already change the name file in another pull request. Thanks!
@arianaescobar Yes, you are right that is why I use _Profesional del Diseño_ But if you all consider _ El/LA Diseñador/Diseñadora_ is better. I'm totally fine. Thanks for the feedback!

@axelvaldez I'm sorry, I'm a human. Humans make mistakes ;)

**Comment by jwishnie** [comment]
@axelvaldez isn't that _exactly_ what a machine would say to convince us it is a human?? ;-)

**Comment by ghost** [comment]
@axelvaldez exactly, you discover my secret :trollface:

**Pull request merged**
