### PR TITLE
Change Arabic translation’s text direction

### PR DESCRIPTION
**Pull request by swashcap**
* **Problem:** GitHub’s stylesheet defaults to left-to-right. This doesn’t work for right-to-left languages, such as Arabic. (See #34)
* **Solution:** Add a `div` with a [`dir="rtl"` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) around the content
* **Testing:** Check out the Arabic Markdown file on my repository: https://github.com/swashcap/designethics/blob/master/ar.md

### CODE REVIEW

**Comment by swashcap** [comment]
Screenshot of what I see (Safari 10.13.3):

arabic-screen

**Comment by swashcap** [comment]
Maybe add a note in the README.md about adding `<div dir="rtl">...</div>` for RTL languages?

**Comment by jwishnie** [comment]
Thank you for the fix! Would be nice if GitHub's markdown processor was bidi-smart... But this solves the problem!

**Comment by jwishnie** [comment]
Sure. I'd accept that pull request!

**Pull request merged**
